### ISSUE TITLE
smaller bundle size

### ISSUE THREAD

**Issue by monoclex** [monoclex/smiley-face-game#11]
we can use preact over react to drop the bundle size some
additionally, when phaser 4 comes out, we can use it to get bundle size down smaller (tree shaking)

(migration from trello)

**Comment by monoclex** [comment]
![do-not-care](https://user-images.githubusercontent.com/9854865/153740567-7673bca1-c258-48b4-99fa-22d7388c7ee1.gif)

**Comment by lrussell887** [comment]
i care pls fix this
